### ISSUE TITLE
Creating Test DB

### ISSUE THREAD

**Issue by PJUllrich** [mircealungu/Zeeguu-Core#3]
I tried to populate my local MySQL database using the zeeguu.populate script, but I get the error:
> Unable to load configuration file (No such file or directory): '/Users/peterullrich/.config/zeeguu/core.cfg'

I ran the script `other/utils/create_test_db.sh` already and it created all tables with 2 seemingly default values. However, the populate.py script still returned the same error.

**Comment by PJUllrich** [comment]
Okay, while writing the issue I actually solved it already, but thought that I'd post it here anyway, also for Timon and in general new people who join the project. The solution lies in the `.travis.yml` file. 

You have to run the following bash command: 

`mkdir -p ~/.config/zeeguu/ && cp testing_default.cfg ~/.config/zeeguu/core_test.cfg`

and then rename the file to `core.cfg` with this command:

`mv ~/.config/zeeguu/core_test.cfg ~/.config/zeeguu/core.cfg`

**Comment by mircealungu** [comment]
@PJUllrich - thanks for posting the answer! 

Do you think that it's worth adding this to a FAQ section, at the end of the `README.md` file? It would be much more findable there than here as a closed issue I think.

**Comment by PJUllrich** [comment]
I updated the Readme in our fork yesterday to explain exactly how to set up Zeeguu-Core for local testing purposes: https://github.com/timonback/Zeeguu-Core/tree/dev

**Comment by mircealungu** [comment]
Nice job!
